version: "3.8"

services:
  myubuntu20s:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.ssh:/root/.ssh
      - $HOME/workspace:/root/workspace
      # mysqld.sockもやるか？
      # .zshrcとかもマウントした
      # - "~/.vscode:.vscode"
